rails-basics-ru/nested-resources/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#index'

  # BEGIN
  # resources :posts do
  #   resources :post_comments, only: [:create, :update, :destroy, :new]
  # end
  # resources :posts
  # scope module: :posts do
  #
  #   resources :post_comments, only: [:create, :update, :destroy, :new]
  # end
  # resources :posts
  # scope module: :posts do
  #   resources :post_comments, only: [:create, :update, :destroy, :new]
  # end
  # END
  resources :posts do
    scope module: :posts do
      resources :post_comments
    end
  end
end

rails-basics-ru/nested-resources/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # BEGIN
  has_many :post_comment
  # END

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

rails-basics-ru/nested-resources/app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  # BEGIN
  belongs_to :post
  # END

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

rails-basics-ru/nested-resources/app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index; end
end

rails-basics-ru/nested-resources/app/controllers/posts/post_comments_controller.rb
# frozen_string_literal: true

class Posts::PostCommentsController < Posts::ApplicationController

  def new
    @post_comment = PostComment.new
  end

  def edit
    @post_comment = PostComment.find params[:id]
  end

  def create
    @post_comment = Post.find(params[:post_id]).post_comment.build(post_params)

    if @post_comment.save
      redirect_to post_path(Post.find(params[:post_id])), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post_comment = PostComment.find params[:id]

    if @post_comment.update(post_params)
      redirect_to @post_comment, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post_comment = PostComment.find params[:id]

    @post_comment.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post_comment).permit(:title, :body)
  end
end

rails-basics-ru/nested-resources/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find params[:id]

    @comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find params[:id]

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find params[:id]

    @post.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

rails-basics-ru/nested-resources/app/views/posts/post_comments/_form.html.slim
= form_with(model: @post_comment, url: post_post_comments_path) do |form|
  = form.label :name
  br
  = @post_comment.errors.full_messages_for(:name).join(' ') if @post_comment.errors.present?
  = form.text_field :title
  br
  = form.label :body
  br
  = form.text_area :body
  .actions
  = form.submit

rails-basics-ru/nested-resources/app/views/posts/post_comments/destroy.html.slim
h1
  | Index#destroy
p
  | Find me in app/views/index/destroy.html.erb

rails-basics-ru/nested-resources/app/views/posts/post_comments/edit.html.slim
h1
  | Edit task
= render 'form', task: @task
= link_to 'Back', root_path
= link_to 'Show', task_path(@task)

rails-basics-ru/nested-resources/app/views/posts/post_comments/new.html.slim
= content_for :title do
  = 'New comment'

== render 'form', post_comment: @post_comment

hr

= link_to 'Back', :back, class: 'btn btn-outline-primary'

rails-basics-ru/nested-resources/app/views/posts/post_comments/show.html.slim
- content_for :title do
  = @post_comment.title
p
  strong.me-2 Body:
  = @post_comment.body

h1
  | Comments
table
  thead
    tr
      th
        | Body
      th[colspan="3"]
  tbody
    - @post_comment.each do |comment|
      tr
        td
          = comment.body
        td
          = link_to 'Edit', post_post_comment_path(comment)
        td
          = link_to 'Destroy', post_post_comment_path(@post_comment), method: :delete, data: { confirm: 'Are you sure?' }
br
hr

.d-flex
  = link_to 'Edit', edit_post_path(@post_comment), class: 'btn btn-outline-primary me-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'

rails-basics-ru/nested-resources/app/views/posts/post_comments/update.html.slim
h1
  | Index#update
p
  | Find me in app/views/index/update.html.erb